schema:
  name: daycare
spring:
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: false
  flyway:
    schemas: ${schema.name}
    locations: classpath:db/migration/common, classpath:db/migration/h2
    table: flyway_history
  h2:
    console:
      enabled: true
      path: /console/
  jackson:
    default-property-inclusion: non_null